### ISSUE TITLE
Should it makes sense to enhance createIpv4Ngpf() method to support both ipv4 and ipv6?

### ISSUE THREAD

**Issue by savula15** [OpenIxia/IxNetwork#27]
https://github.com/OpenIxia/IxNetwork/blob/9409826dad65fe9b76a3f93590a573d985f46d0f/RestApi/Python/Modules/IxNetRestApiProtocol.py#L434

Can we enhance createIpv4Ngpf() (make it generic) method to support both ipv4 and ipv6? and also configBgp() method.

What I'm looking for is to leverage existing RestApi Python modules to test IPv4/Ipv6 and BGPv4/BGPv6.

Thanks

**Comment by hubogee** [comment]
configIpv6Ngpf has been there already.  configBgpIpv6 has got added.  A sample script is bgpIpv6Ngpf.py.  

There is a new and much better tool called RestPy.  Ixia highly recommend this over the predecessor IxNetRestApi library because RestPy has all the wrappers created.  Meaning that you no longer need to create wrappers for any APIs or need to wait for someone to create something for you.  There are sample scripts to show you in the link below.  Scripting is a reflection to the IxNetwork API tree.  So if you're familiar with the API tree, looking at the sample scripts should be intuitive.  Have a look ...

https://github.com/OpenIxia/IxNetwork/tree/master/RestPy
