### ISSUE TITLE
VXlan Encap/Decap 

### ISSUE THREAD

**Issue by memoradi** [OpenIxia/IxNetwork#57]
Hello,

My two IXIA ports are connected to an Arista EOS device. I'd like to measure the performance of VXLAN decapsulation by generating VXLAN traffic from one of the IXIA ports, have Arista decapsulate the VXLAN header, and then forward IPV4 traffic to the other IXIA port. 

(1) Do you have any example for this scenario where decapsulation happens in one direction? I looked at the vxlanNgpf.py but, unlike my case, that consists of two homogenous device groups and bidirectional traffic tests.

(2) If not, can you please comment on if I need to load both my source and destination device groups with the entire VXLAN stack? or only the source DG? 

![image](https://user-images.githubusercontent.com/45773137/56723035-0baa9b00-66fd-11e9-9b10-3d05253cf1aa.png)
Do I need to remove the VTEP stack on the right-hand side to get the above scenario working? 

Thanks!

**Comment by whandjr** [comment]
Hi,

Thanks for your interest.  I checked with my solutions architect and he said this is a configuration question.  He inferred from the question that you probably want your setup to have two uni-directional flow-groups rather than one bi-directional flow-group.  Independent control and extrapolation will be much easier.

You may want to consult with your Ixia SE or contact Ixia technical support for more advice on best practice for configuring IxNetwork VXLAN.  Once they have helped you define the best approach to create the simulation you desire, we can advise on the automation to achive that configuration.

Thanks,
Wes

Wesley Hand
m: 818-312-6752

**Comment by memoradi** [comment]
Hi Wes,

I was able to answer the configuration question using trial & error: 
(1) Create a traffic item in IxNetwork client
(2) Play the traffic through one IXIA port and Arista decapsulates it
(3) Receive the IPV4 traffic at the other port.

![image](https://user-images.githubusercontent.com/45773137/56770445-d5a30080-6768-11e9-852e-e847ecca6302.png)


How can I automate the same process using the Rest API?

**Comment by hubertgee** [comment]
Hi Memoradi,

To automate creating packet headers in a traffic item, please take a look at this sample script:
https://github.com/OpenIxia/IxNetwork/blob/master/RestPy/SampleScripts/createTrafficItemAddPacketHeader.py

This sample script has all the common ones: ethernet, vlan, ipv4, udp and tcp.

Since there are over 400 packet headers, the sample script will not cover every one of them.  When you are looking at the sample script to understand how it’s done using RestPy, vxlan would be “VXLAN”.  How do you find out the spelling of the packet header for scripting?

Here is a step-by-step guide:
https://www.openixia.com/tutorials?subject=ixNetwork/apiBrowser&page=addTrafficItemPacketHeader.html

Regards,
Hubert Gee

**Comment by imehrdad2012** [comment]
@hubertgee Thanks a lot for your timely help & support! Highly appreciate it! The links are very useful.

**Comment by whandjr** [comment]
Hi Mehrdad,

Glad to hear you figured it out.  Here is some additional advice from our PM, in case you wish to consider their approach.

Yes. This is a configuration question. To answer your question, Yes, it is doable and it is very common test scenario.

I guess the sample is for B2B and hence both side has VXLAN like below.

[cid:image001.jpg@01D4FC0C.F3BC7B90]
When test it with DUT, DUT will be the VTEP on right side to do decap/encap. Ixia will emulate host only like below.

[cid:image002.jpg@01D4FC0C.F3BC7B90]


Thanks,
Wes

Wesley Hand
m: 818-312-6752

**Comment by imehrdad2012** [comment]
Wes, thanks for the suggestion. Ideally, I would like to use the next gen framework but did not know how to do it, would you mind attaching the above figures again? It does not show up on my browser.
