### ISSUE TITLE
generateifrequired not regenerating traffic items

### ISSUE THREAD

**Issue by pwlodawi** [OpenIxia/IxNetwork#66]
What is .../ixnetwork/traffic/operations/generateifrequired supposed to do ? I know it should regenerate "dirty" traffic but what does it mean exactly ? Does it recognize NexGen protocols ? 

My case is like follows:
1. I load config. It has some NexGen protocols and traffic items between them configured
2. I start all protocols 
3. When protocols are up I do:  post - http://10.10.0.222:11019/api/v1/sessions/1/ixnetwork/traffic/operations/generateifrequired - {'json': {'arg1': '/api/v1/sessions/1/ixnetwork/traffic'}} and get 202 success
4. I apply and start traffic but traffic fails (100% loss).

If I go to API browser and generate each traffic item one by one using
ixnetwork/traffic/trafficItem/<id-here>/operations/generate and then apply and run traffic it works fine (0% loss)

Best Regards,
PW

**Comment by therkong** [comment]
Traffic generate will update the traffic with learned info from the protocols.  For example, it will fill in the dest mac addresses learned from the ARP Request/Reply done when the protocol is started.
“generate” is per traffic item.  You need to do a loop and generate on each traffic item.
In step 3, please pass in the traffic item in arg 1:   {'json': {'arg1': '/api/v1/sessions/1/ixnetwork/traffic/1'}}.

Regards,

Theresa Kong
Senior Tech Support Engineer
Keysight Technologies

**Comment by pwlodawi** [comment]
API browser shows that generateifrequired doesn't accept traffic item as parameter. 
Shouldn't generateifrequired generate all traffic items if needed ?

**Comment by therkong** [comment]
Yes, I see that generateifRequierd() is for traffic level.  
dirty traffic means the traffic item was marked as Regenerate Required (for example, when editing some traffic option that requires traffic to  be regenerated in order to take effect).   However, traffic item is detected as regenerate required in a subset of cases only, not for all possible cases. It will not catch cases when user makes protocol changes that might impact traffic for example.
You should do generate() on traffic item in order to ensure the learned info fields from the protocols are propagated to traffic items.

**Comment by pwlodawi** [comment]
Ok. I see it's better to forget about generateifrequired and simply loop through traffic items and call generate on each one.
