### ISSUE TITLE
IxnetworkRestAPI on Linux

### ISSUE THREAD

**Issue by egondragon** [OpenIxia/IxNetwork#91]
Hi all
I have installed Ixnetwork API Rest API on Linux **(Binary image is: IxNetworkAPI9.00.1915.16Linux64.bin)**
, it should serve as proxy between Python client and VM used for traffic generation:

```
[user@localhost ixia]$ telnet localhost 11009
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
[user@localhost ixia]$ telnet localhost 8009
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
[user@localhost ixia]$
```

My issue is simple: I cannot connect on port 11009:
Did somebody ever seen this problem ?
Thanks
Regards

**Comment by therkong** [comment]
Hi,

Are you trying to run IxNet RestPy script?
Why are you doing  telnet to localhost?
11009 port is the tcp port that IxNetwork API Server listens on if it is run on Windows machine.

First, you need to install ixNetwork API Server either on Windows machine or Linux box.  There are multiple ways to install on Linux machine.
For example:  on EXSi host, on KVM, on Linux chassis, …etc.

If you have IxNetwork API Server on Windows machine, it’s listening on tcp port 11009;  if it’s running on Linux machine, then it’s listening port 443.

Regards,
Theresa

**Comment by whandjr** [comment]
Hi,

When you start your IxNetwork on windows. Make sure you start it in API Server mode.
[cid:image002.png@01D60E52.D45E5F30]

You can confirm if you did by looking at the title bar of IxNetwork

[cid:image006.png@01D60E53.0C73ABF0]


Instead of trying to telnet to 11009, try opening a internet browser and typing in the address

https://localhost:11009

[cid:image001.png@01D60E52.62D76A00]

Then you should get something like this

Click advanced and then proceed.
[cid:image003.jpg@01D60E53.0C8A1A20]

[cid:image004.jpg@01D60E53.0C8A1A20]
That will bring you to this.
[cid:image005.png@01D60E52.D45E5F30]
Let us know if that gets you going.


Thanks,
Wes

Wesley Hand
m: 818-312-6752

**Comment by therkong** [comment]
Hi egondragon,  did you resolve this issue?  If not, let me know your current status on this and I can work with you.
